# Generated by Django 5.2.7 on 2026-01-01 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'USER',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='TASK',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('running', 'running'), ('completed', 'completed'), ('pending', 'pending')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=50)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_by', to='API.user')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_to', to='API.user')),
            ],
            options={
                'db_table': 'TASK',
                'ordering': ['priority'],
            },
        ),
    ]
