# Generated by Django 6.0 on 2026-01-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_task_assigned_by_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('task_name', 'assigned_by', 'assigned_to')},
        ),
    ]
